name: mds-approximations
channels:
- qiime2
- conda-forge
- defaults
- bioconda
- biocore
dependencies:
- scikit-bio
- click
- python=3.7
- numpy
- scikit-learn=0.19.1
- scipy
- pandas
- jupyter
- matplotlib
